/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package me.sandbox

import com.google.auth.oauth2.GoogleCredentials

class App {
    String token() {
        GoogleCredentials creds = GoogleCredentials.getApplicationDefault()
        if( creds.createScopedRequired() )
            creds = creds.createScoped("https://www.googleapis.com/auth/cloud-platform")

        creds.refreshIfExpired()
        return creds
                .getAccessToken()
                ?.getTokenValue()
                ?.replaceAll(/\.+$/,'')
    }


    static void main(String[] args) {
        println new App().token()
    }
}
